name: Pull Request

on:
  workflow_call:
    inputs:
      GITHUB_TOKEN:
        description: 'GitHub token'
        required: true
        type: string

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ inputs.GITHUB_TOKEN }}
          commit-message: 'Automatic PR: Merge changes to main'
          branch: ${{ github.ref }}
          base: main
          title: 'Automatic PR from ${{ github.ref }}'
          body: |
            Este PR foi criado automaticamente pelo fluxo de trabalho de CI para mesclar alterações de ${{ github.ref }} para main.
