name: Tag Release

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      
      - name: Fetch all tags
        run: git fetch --tags

      - name: Calculate next version
        id: next-version
        run: |
          # Get the highest tag number
          CURRENT_VERSION=$(git describe --tags `git rev-list --tags --max-count=1` 2>/dev/null || echo "v0.0.0")
          echo "Current version: $CURRENT_VERSION"

          # Strip leading 'v' and split into an array
          VERSION_NUM=${CURRENT_VERSION#v}
          IFS='.' read -r -a VERSION_PARTS <<< "$VERSION_NUM"

          # Increment the version
          MAJOR=${VERSION_PARTS[0]}
          MINOR=${VERSION_PARTS[1]}
          PATCH=${VERSION_PARTS[2]}

          # Loop to find the next available tag
          while git rev-parse "v$MAJOR.$MINOR.$PATCH" >/dev/null 2>&1 || git ls-remote --tags origin | grep -q "refs/tags/v$MAJOR.$MINOR.$PATCH"; do
            PATCH=$((PATCH + 1))
          done

          # Create new version
          NEW_VERSION="v$MAJOR.$MINOR.$PATCH"
          echo "New version: $NEW_VERSION"
          echo "::set-output name=tag::$NEW_VERSION"

      - name: Create new tag
        run: |
          git tag ${{ steps.next-version.outputs.tag }}
          git push origin ${{ steps.next-version.outputs.tag }}

    comment:
      needs: tag
      runs-on: ubuntu-latest

      steps:
        - name: Post comment
          uses: dacbd/create-issue-action@main
          with:
            token: ${{ secrets.GH_TOKEN }}
            title: Nova versão disponibilzada
            body: "A new version ${{ needs.tag.outputs.tag }} has been created successfully." 
      
      
      # - name: Post comment
      #   uses: dacbd/create-issue-action@main
      #   with:
      #     token: ${{ secrets.GH_TOKEN }}
      #     title: Nova versão disponibilzada
      #     body: "A new version ${{ needs.tag.outputs.tag }} has been created successfully."
